interface WholeData {
  userId: string;
  username: string;
  percentage: number;
  isFriend: boolean;
  WanderRate: {[key: string]: number}[];
}

const wholeData: WholeData[] = [
  {
    userId: 'faker',
    username: 'faker.T1',
    percentage: 99.1557,
    isFriend: false,
    WanderRate: [
      {전체: 99.1557},
      {서울: 8},
      {경기: 6},
      {인천: 4},
      {부산: 10},
      {대전: 7},
      {대구: 8},
      {울산: 6},
      {광주: 7},
      {강원: 5},
      {제주: 2.45645},
    ],
  },
  {
    userId: 'abc',
    username: 'abc1234',
    percentage: 81.11112,
    isFriend: false,
    WanderRate: [
      {전체: 81.11112},
      {서울: 7},
      {경기: 5},
      {인천: 4},
      {부산: 9},
      {대전: 8},
      {대구: 6},
      {울산: 7},
      {광주: 6},
      {강원: 5},
      {제주: 3.45642},
    ],
  },
  {
    userId: 'tantan',
    username: 'tanya.hill',
    percentage: 78.92152,
    isFriend: false,
    WanderRate: [
      {전체: 78.92152},
      {서울: 10},
      {경기: 3},
      {인천: 2},
      {부산: 0},
      {대전: 0},
      {대구: 1},
      {울산: 0},
      {광주: 0},
      {강원: 27},
      {제주: 0.21652},
    ],
  },
  {
    userId: 'zone',
    username: '地Zone',
    percentage: 99.1557,
    isFriend: false,
    WanderRate: [
      {전체: 99.1557},
      {서울: 15},
      {경기: 10},
      {인천: 5},
      {부산: 10},
      {대전: 5},
      {대구: 8},
      {울산: 4},
      {광주: 7},
      {강원: 6},
      {제주: 0.1557},
    ],
  },
  {
    userId: 'min',
    username: 'castleMin',
    percentage: 81.11112,
    isFriend: false,
    WanderRate: [
      {전체: 81.11112},
      {서울: 12},
      {경기: 8},
      {인천: 5},
      {부산: 15},
      {대전: 7},
      {대구: 10},
      {울산: 6},
      {광주: 7},
      {강원: 5},
      {제주: 6.11112},
    ],
  },
  {
    userId: 'dodo',
    username: 'dodohyung',
    percentage: 78.92152,
    isFriend: false,
    WanderRate: [
      {전체: 78.92152},
      {서울: 12},
      {경기: 8},
      {인천: 5},
      {부산: 15},
      {대전: 7},
      {대구: 10},
      {울산: 6},
      {광주: 7},
      {강원: 5},
      {제주: 0.92152},
    ],
  },
  {
    userId: 'd',
    username: 'bill.sanders',
    percentage: 72.11452,
    isFriend: false,
    WanderRate: [
      {전체: 72.11452},
      {서울: 15},
      {경기: 8},
      {인천: 5},
      {부산: 12},
      {대전: 7},
      {대구: 10},
      {울산: 6},
      {광주: 5},
      {강원: 6},
      {제주: 2.11452},
    ],
  },
  {
    userId: 'e',
    username: 'SSAFY99thTrainee',
    percentage: 70.56784,
    isFriend: false,
    WanderRate: [
      {전체: 70.56784},
      {서울: 14},
      {경기: 9},
      {인천: 4},
      {부산: 13},
      {대전: 8},
      {대구: 11},
      {울산: 7},
      {광주: 6},
      {강원: 5},
      {제주: 3.56784},
    ],
  },
  {
    userId: 'f',
    username: 'debbie.baker',
    percentage: 64.45672,
    isFriend: false,
    WanderRate: [
      {전체: 64.45672},
      {서울: 13},
      {경기: 7},
      {인천: 6},
      {부산: 8},
      {대전: 9},
      {대구: 10},
      {울산: 5},
      {광주: 6},
      {강원: 4},
      {제주: 1.45672},
    ],
  },
  {
    userId: 'g',
    username: 'tienlapspktnd',
    percentage: 56.45645,
    isFriend: false,
    WanderRate: [
      {전체: 56.45645},
      {서울: 11},
      {경기: 5},
      {인천: 4},
      {부산: 10},
      {대전: 8},
      {대구: 9},
      {울산: 6},
      {광주: 7},
      {강원: 3},
      {제주: 3.45645},
    ],
  },
  {
    userId: 'h',
    username: 'alma.lawson',
    percentage: 51.45645,
    isFriend: false,
    WanderRate: [
      {전체: 51.45645},
      {서울: 9},
      {경기: 6},
      {인천: 5},
      {부산: 7},
      {대전: 11},
      {대구: 8},
      {울산: 4},
      {광주: 6},
      {강원: 3},
      {제주: 2.45645},
    ],
  },
  {
    userId: 'i',
    username: 'abc1234',
    percentage: 50.45642,
    isFriend: false,
    WanderRate: [
      {전체: 50.45642},
      {서울: 10},
      {경기: 4},
      {인천: 3},
      {부산: 8},
      {대전: 7},
      {대구: 9},
      {울산: 5},
      {광주: 6},
      {강원: 4},
      {제주: 4.45642},
    ],
  },
  {
    userId: 'j',
    username: 'def5678',
    percentage: 49.21652,
    isFriend: false,
    WanderRate: [
      {전체: 49.21652},
      {서울: 9},
      {경기: 5},
      {인천: 4},
      {부산: 10},
      {대전: 8},
      {대구: 7},
      {울산: 6},
      {광주: 5},
      {강원: 4},
      {제주: 1.21652},
    ],
  },
  {
    userId: 'k',
    username: 'hmm',
    percentage: 48.45645,
    isFriend: false,
    WanderRate: [
      {전체: 48.45645},
      {서울: 8},
      {경기: 6},
      {인천: 4},
      {부산: 10},
      {대전: 7},
      {대구: 8},
      {울산: 6},
      {광주: 7},
      {강원: 5},
      {제주: 2.45645},
    ],
  },
  {
    userId: 'l',
    username: 'sh..',
    percentage: 45.45642,
    isFriend: false,
    WanderRate: [
      {전체: 45.45642},
      {서울: 7},
      {경기: 5},
      {인천: 4},
      {부산: 9},
      {대전: 8},
      {대구: 6},
      {울산: 7},
      {광주: 6},
      {강원: 5},
      {제주: 3.45642},
    ],
  },
  {
    userId: 'm',
    username: 'sigmund',
    percentage: 43.21652,
    isFriend: false,
    WanderRate: [
      {전체: 43.21652},
      {서울: 10},
      {경기: 3},
      {인천: 2},
      {부산: 0},
      {대전: 0},
      {대구: 1},
      {울산: 0},
      {광주: 0},
      {강원: 27},
      {제주: 0.21652},
    ],
  },
];

export default wholeData;
